#!/bin/sh
# tearit-install — one-command bootstrap for a tearit-hq desktop.
#
#   curl -fsSL https://raw.githubusercontent.com/tearitco/tearit-install/main/install.sh | sh -s -- tearit-hq
#
# Positional arg 1 : PRODUCT NAME (default: tearit-hq). Names the install
#                    dir, the launcher command, nothing is hardcoded.
# Env overrides:
#   PREFIX       install root            (default: $HOME/<product>)
#   BINDIR       launcher dir            (default: $HOME/.local/bin)
#   PAYLOAD_REPO owner/repo of payload   (default: tearitco/tearit-hq-payload)
#   PAYLOAD_REF  branch/tag/sha          (default: main)
#   FORCE=1      overwrite a non-empty PREFIX
#   NO_BUILD=1   fetch + place only, skip compile
#   NO_LAUNCHER=1 skip writing the PATH launcher

set -eu

PRODUCT="${1:-tearit-hq}"
PREFIX="${PREFIX:-$HOME/$PRODUCT}"
BINDIR="${BINDIR:-$HOME/.local/bin}"
PAYLOAD_REPO="${PAYLOAD_REPO:-tearitco/tearit-hq-payload}"
PAYLOAD_REF="${PAYLOAD_REF:-main}"

say() { printf '\033[1m[tearit-install]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[tearit-install] FATAL:\033[0m %s\n' "$*" >&2; exit 1; }

say "product : $PRODUCT"
say "prefix  : $PREFIX"
say "payload : $PAYLOAD_REPO@$PAYLOAD_REF"

# --- preflight ----------------------------------------------------------
command -v curl >/dev/null 2>&1 || command -v git >/dev/null 2>&1 \
  || die "need either curl or git on PATH"
command -v tar >/dev/null 2>&1 || command -v git >/dev/null 2>&1 \
  || die "need either tar or git on PATH"

if [ -e "$PREFIX" ] && [ -n "$(ls -A "$PREFIX" 2>/dev/null || true)" ]; then
    [ "${FORCE:-0}" = "1" ] || die "$PREFIX exists and is not empty (set FORCE=1 to overwrite)"
    say "FORCE=1 — removing existing $PREFIX"
    rm -rf "$PREFIX"
fi
mkdir -p "$PREFIX"

# --- fetch payload ----------------------------------------------------------
TMP="$(mktemp -d "${TMPDIR:-/tmp}/tearit-install.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
fetched=""

if command -v curl >/dev/null 2>&1 && command -v tar >/dev/null 2>&1; then
    URL="https://codeload.github.com/$PAYLOAD_REPO/tar.gz/refs/heads/$PAYLOAD_REF"
    say "downloading tarball: $URL"
    if curl -fsSL "$URL" -o "$TMP/payload.tar.gz"; then
        mkdir -p "$TMP/x"
        tar -xzf "$TMP/payload.tar.gz" -C "$TMP/x"
        inner="$(find "$TMP/x" -mindepth 1 -maxdepth 1 -type d | head -1)"
        [ -n "$inner" ] || die "tarball had no top-level dir"
        ( cd "$inner" && tar cf - . ) | ( cd "$PREFIX" && tar xf - )
        fetched="tarball"
    else
        say "tarball fetch failed — will try git clone"
    fi
fi

if [ -z "$fetched" ]; then
    command -v git >/dev/null 2>&1 || die "tarball route failed and git not available"
    say "git clone https://github.com/$PAYLOAD_REPO (ref $PAYLOAD_REF)"
    git clone --depth 1 --branch "$PAYLOAD_REF" \
        "https://github.com/$PAYLOAD_REPO.git" "$TMP/clone" \
      || git clone --depth 1 "https://github.com/$PAYLOAD_REPO.git" "$TMP/clone"
    rm -rf "$TMP/clone/.git"
    ( cd "$TMP/clone" && tar cf - . ) | ( cd "$PREFIX" && tar xf - )
    fetched="git"
fi
say "payload placed ($fetched) in $PREFIX"

[ -f "$PREFIX/bootstrap.sh" ] || die "payload missing bootstrap.sh — wrong repo?"

# --- build ------------------------------------------------------------------
if [ "${NO_BUILD:-0}" = "1" ]; then
    say "NO_BUILD=1 — skipping compile"
else
    say "compiling (this is the slow part)…"
    sh "$PREFIX/bootstrap.sh"
fi

# --- launcher -------------------------------------------------------------
if [ "${NO_LAUNCHER:-0}" != "1" ]; then
    mkdir -p "$BINDIR"
    LAUNCHER="$BINDIR/$PRODUCT"
    cat > "$LAUNCHER" <<EOF
#!/bin/sh
# launcher for $PRODUCT — generated by tearit-install
exec sh "$PREFIX/start.sh" "\$@"
EOF
    chmod +x "$LAUNCHER"
    say "launcher: $LAUNCHER"
    case ":$PATH:" in
        *":$BINDIR:"*) ;;
        *) say "NOTE: $BINDIR is not on your PATH — add:  export PATH=\"$BINDIR:\$PATH\"" ;;
    esac
fi

say "done."
if [ "${NO_LAUNCHER:-0}" = "1" ]; then
    say "start it with:  sh $PREFIX/start.sh"
else
    say "start it with:  $PRODUCT      (or: sh $PREFIX/start.sh)"
fi
